type LandscapeAction = ActionType &
  (
    | "bannerplace"
    | "bannerremove"
    | "bannersetcolour"
    | "bannersetname"
    | "bannersetstyle"
    | "clearscenery"
    | "landlower"
    | "landraise"
    | "landsetheight"
    | "landsetrights"
    | "landsmooth"
    | "largesceneryplace"
    | "largesceneryremove"
    | "largescenerysetcolour"
    | "smallsceneryplace"
    | "smallsceneryremove"
    | "signsetname"
    | "signsetstyle"
    | "surfacesetstyle"
    | "tilemodify"
    | "wallplace"
    | "wallremove"
    | "wallsetcolour"
    | "waterlower"
    | "waterraise"
    | "watersetheight"
  );

type ScenarioEditingAction =
  | "peepspawnplace"
  | "mapchanged_scenarioEditor"
  | "mapchanged_trackDesigner"
  | "mapchanged_trackManager"
  | "changemapsize"
  | "climateset"
  | "parkentranceplace"
  | "parkentranceremove";
