const eventNames = [
  "Balloon pressed",
  "Banner placed",
  "Banner removed",
  "Banner colour set",
  "Banner name set",
  "Banner style set",
  "Cheat set",
  "Scenery cleared",
  "Climate set",
  "Footpath addition placed",
  "Footpath addition removed",
  "Footpath placed",
  "Footpath layout placed",
  "Footpath removed",
  "Game speed set",
  "Guest flags set",
  "Guest name set",
  "Land rights purchased",
  "Land lowered",
  "Land raised",
  "Land height set",
  "Land rights set",
  "Land smoothed",
  "Large scenery placed",
  "Large scenery removed",
  "Large scenery colour set",
  "Load or quit",
  "Map size changed",
  "Maze track placed",
  "Maze track set",
  "Network group modified",
  "Park entrance placed",
  "Park entrance removed",
  "Park marketing purchased",
  "Park date set",
  "Park entrance fee set",
  "Park loan set",
  "Park name set",
  "Park parameter set",
  "Park research funding set",
  "Pause toggle",
  "Peep picked up",
  "Peep spawn placed",
  "Player kicked",
  "Player group set",
  "Ride created",
  "Ride demolished",
  "Ride entrance/exit placed",
  "Ride entrance/exit removed",
  "Ride rating frozen",
  "Ride appearance set",
  "Ride colour scheme set",
  "Ride name set",
  "Ride price set",
  "Ride setting set",
  "Ride status set",
  "Ride vehicle set",
  "Scenario setting set",
  "Sign name set",
  "Sign style set",
  "Small scenery placed",
  "Small scenery removed",
  "Small scenery colour set",
  "Staff fired",
  "Staff hired",
  "Staff colour set",
  "Staff costume set",
  "Staff name set",
  "Staff orders set",
  "Staff patrol area set",
  "Surface style set",
  "Tile modified",
  "Track placed",
  "Track removed",
  "Track brake speed set",
  "Wall placed",
  "Wall removed",
  "Wall colour set",
  "Water lowered",
  "Water raised",
  "Water height set",
  "Map changed in scenario editor",
  "Map changed in track designer",
  "Map changed in track manager",
  "Map size changed",
  "Map changed in title screen",
  "Map changed in game",
  "Map saved",
  "Ride ratings calculated",
  "Stall created",
  "Stall demolished",
  "Stall name set",
  "Stall price set",
  "Stall setting set",
  "Vehicle crashed",
  "Peep set down",
  "Guest generated",
  "Network chat",
  "Network action",
  "Network joined",
  "Network left",
] as const;

export type EventName = (typeof eventNames)[number];
