import { ActionTypes } from "openrct2-extended-hooks";
export const eventTextMap: Record<ActionTypes.ExtendedActionType, string> = {
  landbuyrights: "Land Buy Rights",
  landlower: "Land Lower",
  landraise: "Land Raise",
  landsetheight: "Land Set Height",
  landsetrights: "Land Set Rights",
  landsmooth: "Land Smooth",
  surfacesetstyle: "Surface Set Style",
  tilemodify: "Tile Modify",
  wallplace: "Wall Place",
  wallremove: "Wall Remove",
  wallsetcolour: "Wall Set Colour",
  waterlower: "Water Lower",
  waterraise: "Water Raise",
  watersetheight: "Water Set Height",
  bannerplace: "Banner Place",
  bannerremove: "Banner Remove",
  bannersetcolour: "Banner Set Colour",
  bannersetname: "Banner Set Name",
  bannersetstyle: "Banner Set Style",
  clearscenery: "Clear Scenery",
  footpathadditionplace: "Footpath Addition Place",
  footpathadditionremove: "Footpath Addition Remove",
  footpathplace: "Footpath Place",
  footpathlayoutplace: "Footpath Layout Place",
  footpathremove: "Footpath Remove",
  largesceneryplace: "Large Scenery Place",
  largesceneryremove: "Large Scenery Remove",
  largescenerysetcolour: "Large Scenery Set Colour",
  smallsceneryplace: "Small Scenery Place",
  smallsceneryremove: "Small Scenery Remove",
  smallscenerysetcolour: "Small Scenery Set Colour",
  signsetname: "Sign Set Name",
  signsetstyle: "Sign Set Style",
  mapchanged_scenarioEditor: "Map Changed in Scenario Editor",
  mapchanged_trackDesigner: "Map Changed in Track Designer",
  mapchanged_trackManager: "Map Changed in Track Manager",
  changemapsize: "Map Change Size",
  mapchangesize: "Map Change Size",
  climateset: "Climate Set",
  parkentranceplace: "Park Entrance Place",
  parkentranceremove: "Park Entrance Remove",
  peepspawnplace: "Peep Spawn Place",
  scenariosetsetting: "Scenario Set Setting",
  loadorquit: "Load or Quit",
  mapchanged_titleScreen: "Map Changed in Title Screen",
  mapchanged_inGame: "Map Changed in Game",
  mapsaved: "Map Saved",
  mazeplacetrack: "Maze Place Track",
  mazesettrack: "Maze Set Track",
  ridecreate: "Ride Create",
  ridedemolish: "Ride Demolish",
  rideentranceexitplace: "Ride Entrance/Exit Place",
  rideentranceexitremove: "Ride Entrance/Exit Remove",
  ridefreezerating: "Ride Freeze Rating",
  "ride.ratings.calculate": "Ride Ratings Calculate",
  ridesetappearance: "Ride Set Appearance",
  ridesetcolourscheme: "Ride Set Colour Scheme",
  ridesetname: "Ride Set Name",
  ridesetprice: "Ride Set Price",
  ridesetsetting: "Ride Set Setting",
  ridesetstatus: "Ride Set Status",
  ridesetvehicle: "Ride Set Vehicle",
  stallcreate: "Stall Create",
  stalldemolish: "Stall Demolish",
  stallsetname: "Stall Set Name",
  stallsetprice: "Stall Set Price",
  stallsetsetting: "Stall Set Setting",
  trackplace: "Track Place",
  trackremove: "Track Remove",
  tracksetbrakespeed: "Track Set Brake Speed",
  "vehicle.crash": "Vehicle Crash",
  guestsetflags: "Guest Set Flags",
  guestsetname: "Guest Set Name",
  peeppickup: "Peep Pick Up",
  peepsetdown: "Peep Set Down",
  "guest.generated": "Guest Generated",
  stafffire: "Staff Fire",
  staffhire: "Staff Hire",
  staffsetcolour: "Staff Set Colour",
  staffsetcostume: "Staff Set Costume",
  staffsetname: "Staff Set Name",
  staffsetorders: "Staff Set Orders",
  staffsetpatrolarea: "Staff Set Patrol Area",
  networkmodifygroup: "Network Modify Group",
  "network.chat": "Network Chat",
  "network.action": "Network Action",
  "network.join": "Network Join",
  "network.leave": "Network Leave",
  playerkick: "Player Kick",
  playersetgroup: "Player Set Group",
  balloonpress: "Balloon Press",
  cheatset: "Cheat Set",
  gamesetspeed: "Game Set Speed",
  pausetoggle: "Pause Toggle",
  parkmarketing: "Park Marketing Started",
  parksetdate: "Park Set Date",
  parksetentrancefee: "Park Set Entrance Fee",
  parksetloan: "Park Set Loan",
  parksetname: "Park Set Name",
  parksetparameter: "Park Set Parameter",
  parksetresearchfunding: "Park Set Research Funding",
};
